services:
  api:
    build: 
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  mongodb:
    ports:
      - "27017:27017"

  redis:
    ports:
      - "6379:6379"
