name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: poetry run pytest
        env:
          MONGODB_URL: mongodb://localhost:27017/test_wallet_app
          REDIS_URL: redis://localhost:6379/0
          JWT_SECRET_KEY: test-secret-key

      - name: Run linting
        run: |
          poetry run black . --check
          poetry run ruff check .
          poetry run mypy .

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            your-registry/currency-wallet:latest
            your-registry/currency-wallet:${{ github.sha }}
          cache-from: type=registry,ref=your-registry/currency-wallet:buildcache
          cache-to: type=registry,ref=your-registry/currency-wallet:buildcache,mode=max
